services:
  ros:
    build: .
    container_name: ros_noetic
    command: bash -c "source /opt/ros/noetic/setup.bash && tail -f /dev/null"
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger

    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../Federated-RL-ROS:/root/catkin_ws/src/

