version: "3.9"

services:
  ros:
    build: .
    container_name: ros_noetic
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../Federated-RL-ROS:/root/catkin_ws/src/dev_fl_robot_pkg

